on: push

name: Jira Login

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://securecompliance.atlassian.net/
        JIRA_USER_EMAIL: asonger@securecompliance.co
        JIRA_API_TOKEN: Z41DhMJJ6of36Jj9ElPVFB0B

    - name: Jira TODO
      uses: atlassian/gajira-todo@master
      with:
        project: GA
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
